export enum Category {
    HAMBURGER,
  
    CUSTOMHAM_MEAT,
    CUSTOMHAM_BREAD,
    CUSTOMHAM_CHEESE,
    CUSTOMHAM_VEGETABLE,
    CUSTOMHAM_SAUCE,
    CUSTOMHAM_OTHER,
  
    FRI_FRENCHFRIES,
    FRI_FRIEDCHICKEN,
    FRI_OTHERFRIE,
    FRI_SAUCE,
  
    SANDWICH,
  
    CUSTOMSAND_BASE,
    CUSTOMSANDHOT_CHEESE,
    CUSTOMSANDHOT_VEGETABLE,
    CUSTOMSANDHOT_SAUCE,
    CUSTOMSANDHOT_OTHER,
  
    HOTDOG,
  
    CUSTOMHOTDOG_BASE,

    SALAD,
  
    CUSTOMSALAD_BASE,
    CUSTOMSALAD_CHEESE,
    CUSTOMSALAD_FVEGETABLES,
    CUSTOMSALAD_CVEGETABLES,
    CUSTOMSALAD_SAUCE,
    CUSTOMSALAD_OTHER,

    DESSERT,
  
    DESSERT_BASE,
    DESSERT_TOPPING,
    DESSERT_SNACK,
  
    DRINK
  }
  