package com.koyeb.hamburgeria_backend.Enum;

/*
public enum Category {
    MEAT,
    HAMBURGER,
    SANDWICH,
    CUSTOMIZABLE_SANDWICH,
    CUSTOMIZABLE_HOTDOG,
    HOTDOG,
    DRINK,
    DESSERT,
    D_TOPPING,
    D_SNACK,
    FRIES,
    INGREDIENT,
    VEGETABLE,
    SALAD,
    SALAD_VARIOUS,
    OTHER
}
*/

public enum Category {


    HAMBURGER,
    CUSTOM_BURGER,

    CUSTOMHAM_MEAT,
    CUSTOMHAM_BREAD,
    CUSTOMHAM_CHEESE,
    CUSTOMHAM_VEGETABLE,
    CUSTOMHAM_SAUCE,
    CUSTOMHAM_OTHER,

    FRI_FRENCHFRIES,
    FRI_FRIEDCHICKEN,
    FRI_OTHERFRIE,
    FRI_SAUCE,

    SANDWICH,
    CUSTOM_SANDWICH,

    CUSTOMSAND_BASE,
    CUSTOMSANDHOT_CHEESE,
    CUSTOMSANDHOT_VEGETABLE,
    CUSTOMSANDHOT_SAUCE,
    CUSTOMSANDHOT_OTHER,

    HOTDOG,

    CUSTOMHOTDOG_BASE,

    SALAD,
    CUSTOM_SALAD,

    CUSTOMSALAD_BASE,
    CUSTOMSALAD_CHEESE,
    CUSTOMSALAD_FVEGETABLES,
    CUSTOMSALAD_CVEGETABLES,
    CUSTOMSALAD_SAUCE,
    CUSTOMSALAD_OTHER,

    DESSERT,
    CUSTOM_DESSERT,

    DESSERT_BASE,
    DESSERT_TOPPING,
    DESSERT_SNACK,

    DRINK
}